name: Sharon Hammes
description: 
meta_description: "Sharon Hammes"

markdown: redcarpet
highlighter: true

baseurl: '/'

logo: false
paginate: 15
permalink: /:title


# Details for the RSS feed generator
url:            'sharonhammes.com'
author:         'Sharon Hammes'


